### ISSUE TITLE
Walking is broken.

### ISSUE THREAD

**Issue by aleksiaaa** [Parabot/Missing-hooks#1]
Tile.walkTo throws ugly error on PkHonor.

**Comment by Fryslan** [comment]
Please provide the error.

**Comment by aleksiaaa** [comment]
Its not understandable. Error is like 200 rows of:
odyl58€85!86€96!8675+#+6=√+&g+5!(6"(6!(6_$lgzluzlyzhl

**Comment by JKetelaar** [comment]
Could you show the code that you're using for walking?

**Comment by aleksiaaa** [comment]
Tile.walkTo

**Comment by JKetelaar** [comment]
Please provide some more code
Example:
<code>
if (Players.getMyPlayer != null){
Tile.walkTo(new Tile(2000, 3000));
}
</code>

Please be more specific.

**Comment by aleksiaaa** [comment]
That one you posted wont work for example

**Comment by JKetelaar** [comment]
You're definitely doing something wrong.
I'm closing this one until you've learned either Java correctly or get a correct error output.
