### ISSUE TITLE
PKHonor getDef.getId() NPE

### ISSUE THREAD

**Issue by Fryslan** [Parabot/Missing-hooks#10]
This code is giving met an NPE when setting the id variable.

for (Npc npc : Npcs.getNearest()) {
                Npc current = npc;
                if (current != null && current.getDef() != null) {
                    int id = current.getDef().getId();
                    if (!LoadedNpcsList.getItems().contains(id + " - " + new Monsters().getMonsterByID(id))) {
                        LoadedNpcsList.getItems().add(id + " - " + new Monsters().getMonsterByID(id));
                    }
                }
            }

This is the error:

java.lang.NullPointerException
    at org.rev317.min.api.wrappers.NpcDef.getId(NpcDef.java:21)

I think the class accessor is null but im not sure.

**Comment by Fryslan** [comment]
Oops posted in the wrong section please remove to API Issues.

**Comment by JKetelaar** [comment]
if (Npcs.getNearest() != null)

**Comment by Fryslan** [comment]
Oke will try.

**Comment by Fryslan** [comment]
Still giving me that error:

Npc[] npcs = Npcs.getNearest();
            if(npcs != null) {
                for (Npc npc : npcs) {
                    Npc current = npc;
                    if (current != null && current.getDef() != null) {
                        int id = current.getDef().getId();
                        if (!LoadedNpcsList.getItems().contains(id + " - " + new Monsters().getMonsterByID(id))) {
                            LoadedNpcsList.getItems().add(id + " - " + new Monsters().getMonsterByID(id));
                        }
                    }
                }
            }

**Comment by JKetelaar** [comment]
Resolved as far as I can see.
