### ISSUE TITLE
PKHonor getRealLevel()

### ISSUE THREAD

**Issue by Fryslan** [Parabot/Missing-hooks#11]
Is trowing this error:
java.lang.AbstractMethodError: pkhonor.Client.getCurrentStats()[I
    at org.rev317.min.api.methods.Skill.getCurrentLevel(Skill.java:59)

But the field seems to be fine.

**Comment by JKetelaar** [comment]
Do they have multiple containers for one field?

**Comment by Fryslan** [comment]
this.dE = new int[24];

**Comment by Fryslan** [comment]
Fixed
