### ISSUE TITLE
isLoggedIn Hook Issue

### ISSUE THREAD

**Issue by Fryslan** [Parabot/Missing-hooks#14]
![Image](http://puu.sh/ftfEz/d2d145b610.png)

Wrong Accessor:

![Image](http://puu.sh/ftfN7/a302391200.png)

**Comment by JKetelaar** [comment]
Thanks - Will be resolved in the next commit.

**Comment by danihodovic** [comment]
After grepping through the files it seems like the correct accessor is `boolean ib` in class b.java for Ikov. It seems to work for my scripts when detecting logged in/logged out. I identified the file by comparing it with the Galkon example (Client extended RsApplet which extended Applet) and then tried all of the booleans there. Seems to be detecting loggedIn state correctly.

**Comment by JKetelaar** [comment]
It wasn't an actual issue with the hook @dani-h - We already have this in our client:

``` xml
        <add>
            <classname>b</classname>
            <field>ib</field>
            <methodname>isLoggedIn</methodname>
        </add>
```

This is fixed in the latest release of the 317 Minified API

**Comment by danihodovic** [comment]
Out of curiosity how do you find the hooks? Do you have some sort of automated way. Because manually grepping through and guessing seems very tedious.

Also, where can I find the Ikov hook file? Could you link me? Do you have hooks for prayer, i.e detecting if a certain prayer is activated?

**Comment by JKetelaar** [comment]
We use an automated updater which is based on ASM.

You can find the hooks here: http://bdn.parabot.org/data/hooks/carmeuses/
